CREATE TABLE Products(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    [year] INTEGER NOT NULL CHECK ([year] BETWEEN 1900 AND 2100),
    make VARCHAR(128) NOT NULL COLLATE NOCASE,
    model VARCHAR(128) NOT NULL COLLATE NOCASE,
    [type] VARCHAR(256) NOT NULL COLLATE NOCASE
);
